### ISSUE TITLE
Using FastCoding to serialize objects for database storage

### ISSUE THREAD

**Issue by ciphercom** [nicklockwood/FastCoding#14]
I'm running into crashes when using `FastCoding` to serialize `MTLModel` objects for storage in `YapDatabase`. To get you an overview of what's currently happening: We have our object graph ready and set and currently trying out different methods of persisting it to get the best performance / size setup. I dare to say everything works on our side as `NSKeyedArchiver`, `NSJSONSerialization` and `NSPropertyListSerialization` works just fine, but FastCoding fails on archiving one of our object types. I hope you can help us on integrating your library for this task.

The setup that fails: Trying to archive a `MTLModel` object with several custom subtypes (all subclasses of `MTLModel`). Doing so results in `EXC_BAD_ACCESS` deep in the write methods of FastCoding (we're not using `-preferFastCoding`). Most of the time something bad happens in `FCCacheWrittenObject` when the incremented count should be set on the `_stringCache`. If it helps here are all crash points we experienced so far:

```
object = @"keyNameOfOurClass", cache = coder->_stringCache
static inline NSUInteger FCIndexOfCachedObject(__unsafe_unretained id object, __unsafe_unretained NSMutableDictionary *cache)
{
==>    const void *index = CFDictionaryGetValue((__bridge CFMutableDictionaryRef)cache, (__bridge const void *)object);
```

```
object = @"someStringValueOfOneProperty", cache = coder->_stringCache, count = 32
static inline NSUInteger FCCacheWrittenObject(__unsafe_unretained id object, __unsafe_unretained NSMutableDictionary *cache)
{
    NSUInteger count = (NSUInteger)CFDictionaryGetCount((CFMutableDictionaryRef)cache);
==>    CFDictionarySetValue((CFMutableDictionaryRef)cache, (__bridge const void *)(object), (const void *)(count + 1));
```

Interestingly enough the `NSMutableDictionary *cache` won't print it's entries just the count of key/value pairs. I thought that `CFDictionary` are just toll free bridged so I don't know why they won't list their content with `po` or `-description`

Another object of ours serializes just fine, that's something that puzzles me. Skimming over the property types won't reveal any dangling pointer like an only assigned not strongly hold string for example. When we try to persist the JSON representation of our failing object with FastCoding the serialization works. But then we have this additional step of building the JSON and we could just use NSJSONSerialization. So I conclude it must have something to do with the non fast version of custom `NSCoding` objects and/or the combination of Mantle as our choice to implement `NSCoding`.

I would really love to successfully make use of this promising library, as the result with the serialized JSON by FastCoding was already interesting. I know this is just a broad overview in our problem so don't hesitate to ask away about internals. I'm afraid we only have to exchange code (such as header files) in private as our NDA enforces this.

**Comment by cipherCOM** [comment]
I made another batch import with ``-preferFastCoding`` set to ``YES`` sadly this results in a database that is ~6% bigger (with or without enabled gzip). Is this something that surprises you? If so, should I check my implementation for errors? Apart from that the gain in performance is noticeable, some of it was to be expected as the retrieval process of information for the serialization of Mantle is rather slow. All in all, I would prefer to use ``-preferFastCoding`` because of the speed gains.

We are already gzipping before storing the ``NSData`` object into the database. This saves roughly ~15-20% database size AND results in a faster storing and reading process as less bandwidth is needed and the overhead of archiving seems to be smaller.

Is there any other statistic / metric that interests you? I would be glad if I can give you some insights on how your library behaves on huge? genuine databases like ours.

**Comment by nicklockwood** [comment]
Yes, that is very surprising o_O the fastcoding approach stores less data per encoded instance, do I don't know how that could happen.

Can you send me an example of a single class you have that is larger when encoded with fastCoding than with NSCoding?

I understand that may be too much hassle to extract, but it would help me figure out what's going on.

**Comment by cipherCOM** [comment]
What exactly do you need to analyze it? The interface or also the implementation? Only the FastCoding protocol methods?

**Comment by nicklockwood** [comment]
Actually, one possibility is that FastCoding is simply storing more data than NSCoding.

Do you have properties in your classes that you aren't encoding in your NSCoding implementation, and if so have you excluded those from FastCoding too?

**Comment by cipherCOM** [comment]
Yes, I tried to respect this. I used both methods ``+fastCodingKeys`` and the counterpart of Mantle ``+encodingBehaviorsByPropertyKey`` to ensure both save the same data. I even added the model version integer to FastCoding that Mantle stores automatically.

**Comment by nicklockwood** [comment]
I mostly just want a concrete example of a class that produces more data when fastcoded so I can tinker with it and work out why.

Seeing how you're written your implementation may also give me some insight though. You might be using if differently than I anticipated.

**Comment by cipherCOM** [comment]
For one of our classes this is actually true (smaller storage with FastCoding). I have to check which one does increase the overall database. I think I will soon come up with a code snippet.

**Comment by cipherCOM** [comment]
Okay [here](https://gist.github.com/cipherCOM/ebd23ba8faf0519c21d9) it is. I tried to reduce the fan out as much as possible (ended in these strange ``[NSObject new]`` lines) and the result is still the same but the size difference got smaller. Can I do anything to help you, because I presume this is still a huge mess to inspect?

**Comment by nicklockwood** [comment]
Awesome, thanks!

**Comment by nicklockwood** [comment]
BTW, the description "causes FastCoder to store more bytes than NSKeyedArchiver" is slightly inaccurate. It's still using FastCoder even if you set prefersFastCoding to NO - it's just that it uses FastCoder's NSCoding implementation instead of FastCoder's default implementation.

Unless you are saying that it actually stores more bytes when you use FastCoder with prefersFastCoding = NO than it does when you use a regular NSKeyedArchiver. That would be even more surprising, but harder to diagnose since I don't know how NSKeyedArchiver works internally.

**Comment by cipherCOM** [comment]
Yeah your right. I placed the wrong description for this gist. We have currently two separate 'issues':
1) FastCoding results in a larger byte size than NSKeyedArchiver
2) ``-preferFastCoding`` set to ``YES`` results in a larger byte size than without it

And the gist is about 2)

**Comment by nicklockwood** [comment]
Ah, OK. Those are both interesting (but probably unrelated) problems.

**Comment by cipherCOM** [comment]
Updated my statements above, as 1) is just not right.
